cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('increase-quantity/<pk>/',
         views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/',
         views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/',
         views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('orders/<pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('payment/stripe/', views.StripePaymentView.as_view(), name='payment-stripe'),
    path('webhooks/stripe/', views.stripe_webhook_view, name='stripe-webhook'),

]

ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('profile/', views.ProfileView.as_view(), name='profile')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('', views.StaffView.as_view(), name='staff'),
    path('create/', views.ProductCreateView.as_view(), name='product-create'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('products/<pk>/update/',
         views.ProductUpdateView.as_view(), name='product-update'),
    path('products/<pk>/delete/',
         views.ProductDeleteView.as_view(), name='product-delete'),
]

staff/models.py
from django.db import models

# Create your models here.

staff/forms.py
from django import forms

from cart.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'title',
            'image',
            'description',
            'price',
            'available_colours',
            'available_sizes',
        ]

staff/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import reverse
from django.views import generic
from cart.models import Order, Product
from .forms import ProductForm
from .mixins import StaffUserMixin


class StaffView(LoginRequiredMixin, StaffUserMixin, generic.ListView):
    template_name = 'staff/staff.html'
    queryset = Order.objects.filter(ordered=True).order_by('-ordered_date')
    paginate_by = 20
    context_object_name = 'orders'


class ProductListView(LoginRequiredMixin, StaffUserMixin, generic.ListView):
    template_name = 'staff/product_list.html'
    queryset = Product.objects.all()
    paginate_by = 20
    context_object_name = 'products'


class ProductCreateView(LoginRequiredMixin, StaffUserMixin, generic.CreateView):
    template_name = 'staff/product_create.html'
    form_class = ProductForm

    def get_success_url(self):
        return reverse("staff:product-list")

    def form_valid(self, form):
        form.save()
        return super(ProductCreateView, self).form_valid(form)


class ProductUpdateView(LoginRequiredMixin, StaffUserMixin, generic.UpdateView):
    template_name = 'staff/product_create.html'
    form_class = ProductForm
    queryset = Product.objects.all()

    def get_success_url(self):
        return reverse("staff:product-list")

    def form_valid(self, form):
        form.save()
        return super(ProductUpdateView, self).form_valid(form)


class ProductDeleteView(LoginRequiredMixin, StaffUserMixin, generic.DeleteView):
    template_name = 'staff/product_delete.html'
    queryset = Product.objects.all()

    def get_success_url(self):
        return reverse("staff:product-list")

templates/staff/product_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <a href="{% url 'staff:product-list' %}">Go back to products</a>
                <hr />
                <h4>Create a product</a>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type='submit' class='btn btn-primary'>Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/staff/product_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type='submit' class='btn btn-primary'>Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/staff/product_list.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2 class="text-black">Staff Portal - Products</h2>
                <a href="{% url 'staff:product-create' %}">Create a product</a>
                <div class="card">
                    <div class="card-body">
                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Title.</th>
                                        <th>Price</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for product in products %}
                                    <tr>
                                        <td>{{ product.title }}</td>
                                        <td>${{ product.get_price }}</td>
                                        <td>
                                            <a href="{{ product.get_update_url }}">Update</a>
                                            <a tabindex="0" class="btn btn-sm btn-primary" role='button'
                                                data-html='true' data-toggle='popover' data-trigger='focus'
                                                title='Are you sure you want to delete this product?'
                                                data-content="<a href='{{ product.get_delete_url }}'>Confirm</a>">
                                                X
                                            </a>

                                        </td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="3">You don't have any products</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                        {% if page_obj.has_other_pages %}
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <div class="site-block-27">
                                    <ul>
                                        {% if page_obj.has_previous %}
                                            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                                        {% else %}
                                            <li class='disabled'><span>&laquo;</span></li>
                                        {% endif %}

                                        {% for i in paginator.page_range %}
                                            {% if page_obj.number == i %}
                                                <li class='active'>
                                                    <span>
                                                    {{ i }}
                                                     <span class='sr-only'>(current)</span>
                                                    </span>
                                                </li>
                                            {% else %}
                                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}

                                        {% if page_obj.has_next %}
                                            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                        {% else %}
                                            <li class='disabled'><span>&raquo;</span></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block scripts %}
<script>
    $(function () {
        $("[data-toggle=popover]").popover();
    });
</script>
{% endblock scripts %}

templates/staff/product_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <a href="{% url 'staff:product-list' %}">Go back to products</a>
                <hr />
                <h4>Update product</a>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type='submit' class='btn btn-primary'>Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/staff/staff.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2 class="text-black">Staff Portal</h2>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            {{ request.user.email }}
                        </h5>
                        <hr />
                        <a href="{% url 'staff:product-list' %}">Products</a>
                        <hr />

                        <h5 class="card-title">Recent orders</h5>
                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Reference No.</th>
                                        <th>Date</th>
                                        <th>User</th>
                                        <th>Amount</th>
                                        <th>Payment Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders %}
                                    <tr>
                                        <td><a href="{% url 'cart:order-detail' order.pk %}">#{{ order.reference_number }}</a></td>
                                        <td>{{ order.ordered_date }}</td>
                                        <td>{{ order.user.email }}</td>
                                        <td>${{ order.get_total }}</td>
                                        <td>{% if order.ordered %}Paid{% else %}Not paid{% endif %}</td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="4">You haven't made any orders</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                        {% if page_obj.has_other_pages %}
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <div class="site-block-27">
                                    <ul>
                                        {% if page_obj.has_previous %}
                                            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                                        {% else %}
                                            <li class='disabled'><span>&laquo;</span></li>
                                        {% endif %}

                                        {% for i in paginator.page_range %}
                                            {% if page_obj.number == i %}
                                                <li class='active'>
                                                    <span>
                                                    {{ i }}
                                                     <span class='sr-only'>(current)</span>
                                                    </span>
                                                </li>
                                            {% else %}
                                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}

                                        {% if page_obj.has_next %}
                                            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                        {% else %}
                                            <li class='disabled'><span>&raquo;</span></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}